# AUtomatic Differentiation
back propagation

In [18]:
import torch
x = torch.ones(5)
y = torch.zeros(3)
w = torch.rand(5,3, requires_grad=True)
b = torch.rand(3, requires_grad=True)
z = torch.matmul(x, w) + b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z,y)

![计算图](https://pytorch.org/tutorials/_images/comp-graph.png)  
w 和 b 是参数，需要优化
计算损失函数关于参数的梯度，使用requires_grad设置

In [19]:
print(z.grad_fn)
print(loss.grad_fn)

计算损失函数关于参数的偏导$\frac{\partial loss}{\partial w}$ 及 $\frac{\partial loss}{\partial b}$  
`loss.backward()`

In [20]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.3231, 0.3262, 0.3203],
        [0.3231, 0.3262, 0.3203],
        [0.3231, 0.3262, 0.3203],
        [0.3231, 0.3262, 0.3203],
        [0.3231, 0.3262, 0.3203]])
tensor([0.3231, 0.3262, 0.3203])


停止梯度跟踪
`torch.no_grad()`

In [21]:
z = torch.matmul(x,w)+b
print(z.requires_grad)
with torch.no_grad():
    z = torch.matmul(x,w)+b
print(z.requires_grad)

True
False


## Tensor Gradients and Jacobian Products

* t() 转置
* retain_graph


In [22]:
inp = torch.eye(4, 5, requires_grad=True)
out = (inp+1).pow(2).t()
out.backward(torch.ones_like(out), retain_graph=True)
print(inp.grad)
out.backward(torch.ones_like(out), retain_graph=True)
print(inp.grad)
inp.grad.zero_()
out.backward(torch.ones_like(out), retain_graph=True)
print(inp.grad)

tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])
tensor([[8., 4., 4., 4., 4.],
        [4., 8., 4., 4., 4.],
        [4., 4., 8., 4., 4.],
        [4., 4., 4., 8., 4.]])
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])
